version: "3.8"

services:

  setup-contracts:
    container_name: hardhat
    build:
      context: ./packages/contracts
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY}
    volumes:
      - contracts-data:/usr/src/app/packages/contracts/deployments
    networks:
      - hardhat_network
    command: ["/usr/src/app/index.sh"]
    extra_hosts:
      - "localhost:host-gateway"
      
  backend:
    container_name: backend
    build:
      context: ./packages/backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - hardhat_network
    extra_hosts:
      - "localhost:host-gateway"

  frontend:
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://localhost:4000
    networks:
      - hardhat_network
    extra_hosts:
      - "localhost:host-gateway"

      
networks:
  hardhat_network:
    driver: bridge

volumes:
  contracts-data: